# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import observation_action_pb2 as observation__action__pb2


class RLCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Step = channel.unary_unary(
                '/rlc.RLC/Step',
                request_serializer=observation__action__pb2.ActionData.SerializeToString,
                response_deserializer=observation__action__pb2.ObservationData.FromString,
                )
        self.Reset = channel.unary_unary(
                '/rlc.RLC/Reset',
                request_serializer=observation__action__pb2.Empty.SerializeToString,
                response_deserializer=observation__action__pb2.ObservationData.FromString,
                )
        self.Terminate = channel.unary_unary(
                '/rlc.RLC/Terminate',
                request_serializer=observation__action__pb2.Empty.SerializeToString,
                response_deserializer=observation__action__pb2.Empty.FromString,
                )


class RLCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Terminate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RLCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=observation__action__pb2.ActionData.FromString,
                    response_serializer=observation__action__pb2.ObservationData.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=observation__action__pb2.Empty.FromString,
                    response_serializer=observation__action__pb2.ObservationData.SerializeToString,
            ),
            'Terminate': grpc.unary_unary_rpc_method_handler(
                    servicer.Terminate,
                    request_deserializer=observation__action__pb2.Empty.FromString,
                    response_serializer=observation__action__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rlc.RLC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RLC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rlc.RLC/Step',
            observation__action__pb2.ActionData.SerializeToString,
            observation__action__pb2.ObservationData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rlc.RLC/Reset',
            observation__action__pb2.Empty.SerializeToString,
            observation__action__pb2.ObservationData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Terminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rlc.RLC/Terminate',
            observation__action__pb2.Empty.SerializeToString,
            observation__action__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
